version: '2'
services:
  postgres:
    image: postgres
    volumes:
      - ./db/contacts.sql:/docker-entrypoint-initdb.d/contacts.sql
      - ./db/projects.sql:/docker-entrypoint-initdb.d/projects.sql
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
  redis:
    image: redis
  server:
    depends_on:
      - postgres
      - redis
    image: jsixc/node-yarn-app:7
    volumes:
      - ./:/home/app
    ports:
      - "3000:3000"
      - "9966:9966"
    environment:
      DB_URL: "postgres://postgres:pwd@postgres:5432/postgres"
      PORT: 3000
      API_HOST: "http://localhost:3000/api"
      REDIS_URL: "redis://redis:6379"
      SESSION_KEY: secret # fake key for development environment
      AUTH0_CLIENT_ID: $AUTH0_CLIENT_ID
      AUTH0_CLIENT_SECRET: $AUTH0_CLIENT_SECRET
      AUTH0_CALLBACK_URL: $AUTH0_CALLBACK_URL
      AUTH0_DOMAIN: $AUTH0_DOMAIN
