version: '2'
services:
  postgres:
    image: postgres
    volumes:
      # - pgdata:/var/lib/postgresql/data
      - ./scripts/contacts.sql:/docker-entrypoint-initdb.d/contacts.sql
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
  web:
    depends_on:
      - postgres
    image: erasche/postgrest
    ports:
      - "3000:3000"
    environment:
      DB_URI: "postgres://postgres:pwd@postgres:5432/postgres"
      DB_SCHEMA: public
      DB_ANON_ROLE: postgres
# volumes:
  # pgdata:
